FROM oraclelinux:7-slim
ARG VERSION
COPY ./packages/oracle-graph-${VERSION}.x86_64.rpm /tmp
RUN yum install -y java-11-openjdk-devel unzip expect numactl vim \
 && yum clean all \
 && rm -rf /var/cache/yum/* \
 && rpm -ivh /tmp/oracle-graph-${VERSION}.x86_64.rpm \
 && rm /tmp/oracle-graph-${VERSION}.x86_64.rpm
EXPOSE 7007
ENV PATH=$PATH:/opt/oracle/graph/pgx/bin
WORKDIR /opt/oracle/graph/pgx/bin
CMD ["sh", "start-server"]
