FROM oraclelinux:7-slim
ARG VERSION

COPY ./packages/oracle-graph-client-${VERSION}.zip /
RUN yum install -y java-11-openjdk-devel unzip \
 && yum clean all \
 && rm -rf /var/cache/yum/* \
 && unzip /oracle-graph-client-${VERSION}.zip
ENV PATH=$PATH:/oracle-graph-client-${VERSION}/bin
WORKDIR /oracle-graph-client-${VERSION}/bin
