FROM openjdk:11-oracle
ARG VERSION
RUN echo ${VERSION}

COPY ./tmp/oracle-graph-${VERSION}.x86_64.rpm /tmp
RUN rpm -ivh /tmp/oracle-graph-${VERSION}.x86_64.rpm
ENV PATH=$PATH:/opt/oracle/graph/bin
WORKDIR /opt/oracle/graph/bin
