FROM oracle/openjdk:8
ARG VERSION
RUN echo ${VERSION}

COPY ./tmp/oracle-graph-${VERSION}.x86_64.rpm /tmp
RUN rpm -ivh /tmp/oracle-graph-${VERSION}.x86_64.rpm
RUN yum install -y expect
EXPOSE 7007
ENV PATH=$PATH:/opt/oracle/graph/pgx/bin
WORKDIR /opt/oracle/graph/pgx/bin
CMD ["sh", "start-server"]
