CREATE USER retail IDENTIFIED BY Welcome1
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

ALTER USER retail QUOTA UNLIMITED ON users;

GRANT CONNECT TO retail;
GRANT RESOURCE TO retail;
GRANT CREATE VIEW TO retail;

EXIT
