CREATE USER paysim IDENTIFIED BY Welcome1
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

ALTER USER paysim QUOTA UNLIMITED ON users;

GRANT CONNECT TO paysim;
GRANT RESOURCE TO paysim;
GRANT CREATE VIEW TO paysim;

EXIT
